<?php
// CiviCRM settings metadata for the Goonj Event Registration Afform.
// Admins can override any value via `Setting.set` API or Admin UI.

return [
  'goonj_event_registration_success_url' => [
    'group_name' => 'Goonj Event Registration',
    'group' => 'goonj_event_registration',
    'name' => 'goonj_event_registration_success_url',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '/event-sucess/',
    'add' => '6.0',
    'title' => 'Event Registration - Success redirect URL',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'URL to redirect to after at least one Participant is created.',
    'help_text' => NULL,
  ],
  'goonj_event_registration_duplicate_url' => [
    'group_name' => 'Goonj Event Registration',
    'group' => 'goonj_event_registration',
    'name' => 'goonj_event_registration_duplicate_url',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '/event-duplicate/',
    'add' => '6.0',
    'title' => 'Event Registration - Duplicate redirect URL',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'URL to redirect to when every selected event was already registered.',
    'help_text' => NULL,
  ],
  'goonj_event_registration_filter_label' => [
    'group_name' => 'Goonj Event Registration',
    'group' => 'goonj_event_registration',
    'name' => 'goonj_event_registration_filter_label',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'Event Type',
    'add' => '6.0',
    'title' => 'Event Registration - Filter label',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Label for the Event Type filter dropdown.',
    'help_text' => NULL,
  ],
  'goonj_event_registration_filter_help' => [
    'group_name' => 'Goonj Event Registration',
    'group' => 'goonj_event_registration',
    'name' => 'goonj_event_registration_filter_help',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'Pick a type to filter the Event list below.',
    'add' => '6.0',
    'title' => 'Event Registration - Filter help text',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Help text shown under the Event Type filter.',
    'help_text' => NULL,
  ],
  'goonj_event_registration_all_types_label' => [
    'group_name' => 'Goonj Event Registration',
    'group' => 'goonj_event_registration',
    'name' => 'goonj_event_registration_all_types_label',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'All types',
    'add' => '6.0',
    'title' => 'Event Registration - All types label',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Label for the default option in the Event Type filter.',
    'help_text' => NULL,
  ],
];
