name: Docker Tests

on:
  pull_request:
    types: [labeled]
    branches:
      - develop
      - master

jobs:
  checkout-and-test:
    if: contains(github.event.pull_request.labels.*.name, 'in review')
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=chromium

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots
          path: playwright-report/screenshots
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-videos
          path: playwright-report/videos
          retention-days: 5

      - name: Stop services
        run: docker compose down
